## Stage 1 : Gradle build produces the application executable jar
FROM gradle:jdk17 as builder

WORKDIR /stella
COPY --chown=gradle:gradle . .
RUN gradle build


## Stage 2 : Final image with JRE and application executable jar
FROM openjdk:17-jdk-alpine3.14

# Copy JAR into container image
COPY --from=builder /stella/build/libs/stella-0.0.1-SNAPSHOT.jar stella.jar

# Run application using executable jar application
CMD ["java", "-jar", "stella.jar"]
