FROM openjdk:17.0.1-jdk-slim

# Copy JAR into container image
COPY build/libs/stella-0.0.1-SNAPSHOT.jar stella.jar

# Run application using executable jar application 
CMD ["java", "-jar", "stella.jar"]
