FROM openjdk:17-jdk-alpine3.16

# Copy JAR into container image
COPY build/libs/stella-0.0.1-SNAPSHOT.jar stella.jar

# Run application using executable jar application 
CMD ["java", "-jar", "stella.jar"]
